### ISSUE TITLE
Running Workout Screen

### ISSUE THREAD

**Issue by MrAsterisco** [MrAsterisco/Gymspot#10]
# Overview
The Running Workout screen shows a running workout and allows one to control the current step, play/pause/stop the workout, and make on-the-fly changes to the routine and each exercise.

## Subtasks

- [ ] Show current step
- [ ] Allow changing values
- [ ] Show rest steps
- [ ] Allow skipping steps
- [ ] Support increasing or decreasing the rest time
- [ ] Play/pause/stop the workout
- [ ] Cancel the workout
- [ ] Allow adding new steps
